FROM python:3.7

WORKDIR /app

COPY ./poetry.lock ./pyproject.toml /app/

RUN pip install poetry

COPY api /app/api

RUN python -m poetry config virtualenvs.create false

RUN python -m poetry install --no-dev

CMD ["uvicorn", "api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
