[tool.poetry]
name = "apisrun"
version = "0.1.0"
description = ""
authors = ["Jose Salas <josephsalas.developer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
